### PR TITLE
Do not use Provider component imported from jotai

### LINKED ISSUE #10: Jotai-x broke plain Jotai's provider-less atoms
**Description**

If a `jotai-x` Provider component is used it automatically wraps plain `jotai`'s '[provider-less](https://jotai.org/docs/core/provider#:~:text=If%20an%20atom%20is%20used%20in%20a%20tree%20without%20a%20Provider%2C%20it%20will%20use%20the%20default%20state.%20This%20is%20so%2Dcalled%20provider%2Dless%20mode.)' atoms inside that provider component, making the provider-less atom, provided.
Hence I cannot use provider-less atoms anymore, if I set an atom value within a `jotai-x` provider the `useAtom` getter outside the `jotai-x` provider won't get the updated value.

**Steps**

1. Create a `jotai-x` atomStore with `createAtomStore(..)`
2. Create a `jotai` atom with `atom(...)`
3. Set the `jotai` atom within the `<atom>Provider` created in step 1
4. Read the `jotai` atom outside the `<atom>Provided`

Sandbox [here](https://codesandbox.io/p/sandbox/jotai-x-broke-providerless-x2p6hr?file=%2Fsrc%2FApp.tsx%3A20%2C58).

**Expectation**
I'm expecting `jotai-x` Providers to not interfere with plain `jotai` 'provider-less' atoms

### PR DESCRIPTION
**Pull request by 12joan**
**Description**

Fixes #10

See changesets.

### CODE REVIEW

**Comment by 12joan** [comment]
Confirmed [fixes issue sandbox](https://codesandbox.io/p/sandbox/jotai-x-broke-providerless-forked-r6vnw9?file=%2Fsrc%2FApp.tsx%3A16%2C26), and causes no test failures in Plate

**Comment by valerio-pescatori** [comment]
@12joan can you make the sandbox public pls? 
btw thank you for the quick fix!

**Review by zbeyens — APPROVED** [review]

**Pull request merged**
